(ns app.db.kits.connect.core
  (:require [app.db.kits.connect.LRG-16-60.subs]
            [app.db.kits.connect.LRG-16-60.events]
            [app.db.kits.connect.LRG-16-61.subs]
            [app.db.kits.connect.LRG-16-61.events]
            [app.db.kits.connect.TRV-5-60.subs]
            [app.db.kits.connect.NRG-16-60-I.subs]
            [app.db.kits.connect.NRG-16-60-II.subs]
            [app.db.kits.connect.NRG-16-61.subs]
            [app.db.kits.connect.NRG-26-60.subs]
            [app.db.kits.connect.NRGT-26-2.subs]
            [app.db.kits.connect.NRR-2-60.subs]
            [app.db.kits.connect.NRR-2-60.events]
            [app.db.kits.connect.NRR-2-60-3C.subs]
            [app.db.kits.connect.NRR-2-60-3C.events]
            [app.db.kits.connect.NRR-2-61.subs]
            [app.db.kits.connect.NRR-2-61.events]
            [app.db.kits.connect.NRR-2-61-3C.subs]
            [app.db.kits.connect.NRR-2-61-3C.events]
            [app.db.kits.connect.LRR-1-60.subs]
            [app.db.kits.connect.URS-60.subs]
            [app.db.kits.connect.URS-61.subs]
            [app.db.kits.connect.URB-60.subs]
            [app.db.kits.connect.URW-60.subs]
            [app.db.kits.connect.URW-60.events]))
